version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.11

    steps:
      - checkout
      - run:
          name: Install Bun
          command: |
            curl -fsSL https://bun.sh/install | bash
            echo 'export BUN_INSTALL="$HOME/.bun"' >> $BASH_ENV
            echo 'export PATH="$BUN_INSTALL/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Install Dependencies
          command: cd app && bun install

      - run:
          name: Run Static Tests
          command: cd app && bun run test:static

      - run:
          name: Run Unit Tests
          command: cd app && bun run test:unit

      - run:
          name: Build for Production
          command: cd app && bun run build

workflows:
  version: 2
  build:
    jobs:
      - build
