version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.11

    steps:
      - checkout
      - run:
          name: Install Bun
          command: |
            curl -fsSL https://bun.sh/install | bash
            echo 'export BUN_INSTALL="$HOME/.bun"' >> $BASH_ENV
            echo 'export PATH="$BUN_INSTALL/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Install Dependencies
          command: cd web-ext && bun install

      - run:
          name: Run Tests
          command: cd web-ext && bun run test

      - run:
          name: Build for Chrome Production
          command: cd web-ext && bun run build

      - run:
          name: Build for Firefox Production
          command: cd web-ext && bun run build:firefox

workflows:
  version: 2
  build:
    jobs:
      - build
