name: 📝 Documentation
description: Propose changes and improvements to Docs.
labels: ["Status: Needs Investigation", "Type: Documentation"]
title: "[docs]: "
body:
  - type: textarea
    attributes:
      label: Why do the Docs need this improvement?
      description: A clear and concise description of the issue.  What is the motivation for this change? How will this change benefit the community?
      placeholder: "I would like to contribute to JSON Schema Docs 📑 by..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the changes/solution you suggest
      description: A clear and concise description of what you want to happen
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the issue here
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Are you working on this?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
