name: Documentation
description: Request updates or additions to the documentation.
title: "Docs: [Brief description of the request]"
labels: ["Status: Needs Investigation", "Type: Documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an update or addition to the documentation! Please fill out the details below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Describe the missing or unclear documentation."
      placeholder: "Explain the specific area or topic that requires documentation."

  - type: textarea
    id: reason_for_update
    attributes:
      label: Reason for Update
      description: "Why is this documentation update necessary?"
      placeholder: "Explain why the current documentation is insufficient."

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: "Add any other relevant information, like links or examples."
      placeholder: "Include any additional context or related issues here."
